version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'timeSheet'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3310:3310'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    networks:
      devops-network:

  devops-project:
    build: .\
    image: timesheet
    container_name: "devOpsProject_container"
    ports:
      - "8088:8088"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3310/timeSheet
    networks:
      devops-network:

networks:
  devops-network:
    driver: bridge
