
version: "2.2"
services:
  Candidate:
    container_name: candidate-service
    build: ./candidate-service
    ports:
      - "8083:8083"
    hostname: candidate
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    image: "candidate-service"
    depends_on:
      - Eureka
      - Mongo


  Candidature:
    container_name: candidature-service
    build: ./candidature-service
    ports:
      - "8084:8084"
    hostname: candidate
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    image: "candidature-service"
    depends_on:
      - Eureka

  Employee:
    container_name: employee-service
    build: ./employee-service
    ports:
      - "8087:8087"
    hostname: employee
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    image: "employee-service"
    depends_on:
      - Eureka

  Evaluation:
    container_name: evaluation-service
    build: ./evalulation-service
    ports:
      - "8085:8085"
    hostname: evaluation
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    image: "evaluation-service"
    depends_on:
      - Eureka

  Offre:
    container_name: offre-service
    build: ./offre-service
    ports:
      - "8086:8086"
    hostname: offre
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    image: "offre-service"
    depends_on:
      - Eureka

  Auth:
    container_name: auth-service
    build: ./auth-service
    ports:
      - "8081:8081"
    hostname: authentification
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    image: "auth-service"
    depends_on:
      - Eureka

  Gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "8054:8054"
    hostname: api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    image: "api-gateway"
    depends_on:
      - Eureka

  node:
    container_name: node-service
    image: "node-service"
    build: ./node-service
    ports:
      - "3000:5000"
    hostname: node-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=eureka-server
    depends_on:
      - "Eureka"
      - "Mongo"
    command: "node ./index.js"

  Eureka:
    container_name: eureka-server
    build: ./eureka-server
    ports:
      - "8761:8761"
    hostname: eureka-server
    image: "eureka-server"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  Mongo:
    container_name: Mongo
    image: "mongo:5-focal"
    ports:
      - "27017:27017"
    hostname: mongodb
    depends_on:
      - "Eureka"
